### ISSUE TITLE
no support for ARM?

### ISSUE THREAD

**Issue by ratio91** [JoeRu/Webhook2MQTT#1]
Thank for this project!

However, it does not run on my raspberry Pi:

```
 => ERROR [webhook2mqtt internal] load metadata for docker.io/tiangolo/meinheld-gunicorn-flask:latest                                                    1.7s
------
 > [webhook2mqtt internal] load metadata for docker.io/tiangolo/meinheld-gunicorn-flask:latest:
------
failed to solve: tiangolo/meinheld-gunicorn-flask:latest: no match for platform in manifest sha256:82142f3fafd6ce1678b77d07adc98f577007453662d363c5ea60a3b4e686341e: not found
```

is this just a building error (I can build elsewhere) or does it generally not support arm at the moment?
Thank you!

**Comment by JoeRu** [comment]
Hi
you're right - the flask image has no arm support - but that's more an "issue" of this project: https://github.com/tiangolo/meinheld-gunicorn-flask-docker

readme.md recommend to build the image locally.
